# Fonts
font_family      Caskaydiacove Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.0
enable_audio_bell yes
sync_to_monitor yes
repaint_delay 10
input_delay 3
# Window Layout
window_padding_width 2
hide_window_decorations yes
confirm_os_window_close 0

# Transparency & Blur
background_opacity 0.85
background_blur 1

# Master Color Palette (Synced with Waybar)
background #11111b
foreground #cdd6f4


# Cursor & Selection
cursor #ff9800
cursor_text_color #11111b
selection_background #ff9800
selection_foreground #11111b

# --- ADD THESE LINES FOR SMOOTH CURSOR ---
cursor_shape block
cursor_blink_interval 0.5 ease-in-out
cursor_trail 3
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2
linux_display_server wayland
# -----------------------------------------

# URL Underline
url_color #8caaee

# The 16 Terminal Colors
# Black
color0 #1e1e2e
color8 #585b70

# Red
color1 #f38ba8
color9 #f38ba8

# Green
color2  #a6e3a1
color10 #a6e3a1

# Yellow / Orange (Mapped to your accent colors)
color3  #ff9800
color11 #ff5722

# Blue
color4  #8caaee
color12 #8caaee

# Magenta
color5  #f5c2e7
color13 #f5c2e7

# Cyan
color6  #94e2d5
color14 #94e2d5

# White
color7  #bac2de
color15 #a6adc8

# Tab Bar Aesthetics
tab_bar_edge top
tab_bar_style powerline
tab_powerline_style slanted
tab_bar_min_tabs 2

# Tab Bar Colors (Matching your Waybar palette)
active_tab_foreground   #11111b
active_tab_background   #ff9800
active_tab_font_style   bold
inactive_tab_foreground #cdd6f4
inactive_tab_background #1e1e2e
inactive_tab_font_style normal
tab_bar_background      #11111b