general {
    lock_cmd = hyprlock                         # Hyprlock natively avoids multiple instances
    before_sleep_cmd = loginctl lock-session    # Lock before the system goes to sleep.
    after_sleep_cmd = hyprctl dispatch dpms on  # Turn on the display when waking up.
}

# 1. Dim the screen and turn off keyboard after inactivity
listener {
    timeout = 3450                                # DIM_TIMEOUT
    on-timeout = brightnessctl -s set 10          # Dim monitor and turn off keyboard
    on-resume = brightnessctl -r                  # Restore monitor and load last keyboard effect
}

# 2. Lock the screen after inactivity
listener {
    timeout = 3600                                # LOCK_TIMEOUT
    on-timeout = loginctl lock-session            
}

# 3. Turn off the display after inactivity
listener {
    timeout = 3630                                # DPMS_TIMEOUT
    on-timeout = hyprctl dispatch dpms off        
    on-resume = hyprctl dispatch dpms on          
}