# ==========================================
# LAYER RULES (System UI Blur)
# ==========================================

layerrule {
    name = waybar_blur
    match:namespace = ^(waybar)$
    blur = on
    ignore_alpha = 0.0
}

layerrule {
    name = rofi_blur
    match:namespace = ^(rofi)$
    blur = on
    ignore_alpha = 0.0
}

layerrule {
    name = swaync_control_blur
    match:namespace = ^(swaync-control-center)$
    blur = on
    ignore_alpha = 0.0
}

layerrule {
    name = swaync_notification_blur
    match:namespace = ^(swaync-notification-window)$
    blur = on
    ignore_alpha = 0.0
}

layerrule {
    name = wlogout_blur
    match:namespace = ^(logout_dialog)$
    blur = on
    ignore_alpha = 0.0
    animation = popin 80%
}


# Float utility windows and center them
windowrule {
    name = calc_float
    match:class = ^(org\.gnome\.Calculator)$
    float = 1
}

windowrule {
    name = pavucontrol_float
    match:class = ^(pavucontrol)$
    float = 1
    size = 800 600
}

windowrule {
    name = blueman_float
    match:class = ^(blueman-manager)$
    float = 1
    center = 1
}

# Float Polkit Authentication Agents
windowrule {
    name = polkit_float
    match:class = ^(polkit-gnome-authentication-agent-1)$
    float = 1
    center = 1
}

# Float file picker dialogs (Save/Open)
windowrule {
    name = open_file_float
    match:title = ^(Open File)$
    float = 1
}

windowrule {
    name = save_file_float
    match:title = ^(Save File)$
    float = 1
}
