# ==========================================
# LAYER RULES (System UI Blur)
# ==========================================

layerrule {
    name = waybar_blur
    match:namespace = ^(waybar)$
    blur = on
    ignore_alpha = 0.0
}

layerrule {
    name = rofi_blur
    match:namespace = ^(rofi)$
    blur = on
    ignore_alpha = 0.0
}

layerrule {
    name = swaync_control_blur
    match:namespace = ^(swaync-control-center)$
    blur = on
    ignore_alpha = 0.0
}

layerrule {
    name = swaync_notification_blur
    match:namespace = ^(swaync-notification-window)$
    blur = on
    ignore_alpha = 0.0
}

layerrule {
    name = wlogout_blur
    match:namespace = ^(logout_dialog)$
    blur = on
    ignore_alpha = 0.0
    animation = popin 80%
}
